CREATE DATABASE hibernate_db;

CREATE TABLE Person
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age  int CHECK ( age < 100 )
);

CREATE TABLE Item
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int          references Person (id) ON DELETE SET NULL,
    item_name VARCHAR(100) NOT NULL
);

INSERT INTO Person (name, age)
VALUES ('Tom', 35),
       ('Bob', 52),
       ('Katy', 14);

INSERT INTO Item(person_id, item_name)
VALUES (1, 'Book'),
       (1, 'AirPods'),
       (2, 'Iphone'),
       (3, 'Laptop'),
       (3, 'TV'),
       (3, 'Playstation');
