CREATE DATABASE test_app_db;

DROP TABLE public.ingredient_recipe;
DROP TABLE public.ingredients;
DROP TABLE public.recipes;


CREATE TABLE public.ingredients
(
    ingredient_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE public.meal
(
    meal_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE public.recipes
(
    recipe_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_name        varchar(255) NOT NULL UNIQUE,
    recipe_description text         NOT NULL,
    meal_id            bigint,
    foreign key (meal_id) references meal (meal_id)
);

CREATE TABLE public.ingredient_recipe
(
    ingredient_recipe_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id        bigint NOT NULL,
    foreign key (ingredient_id) references ingredients (ingredient_id),
    recipe_id            bigint NOT NULL,
    foreign key (recipe_id) references recipes (recipe_id)
);

INSERT INTO public.ingredients (ingredient_name)
VALUES ('Eggplant'),
       ('Tomato'),
       ('Cucumber'),
       ('Potato'),
       ('Onion'),
       ('Carrot'),
       ('Cabbage'),
       ('Broccoli'),
       ('Bell Pepper'),
       ('Zucchini'),
       ('Spinach'),
       ('Cauliflower'),
       ('Lettuce'),
       ('Radish'),
       ('Asparagus'),
       ('Apricot'),
       ('Pear'),
       ('Apple'),
       ('Grape'),
       ('Orange'),
       ('Banana'),
       ('Strawberry'),
       ('Kiwi'),
       ('Pineapple'),
       ('Mango'),
       ('Watermelon'),
       ('Cherry'),
       ('Plum'),
       ('Peach'),
       ('Blueberry'),
       ('Milk'),
       ('Sour cream'),
       ('Cheese'),
       ('Cream'),
       ('Butter'),
       ('Yogurt'),
       ('Cottage Cheese'),
       ('Whipped Cream'),
       ('Condensed Milk'),
       ('Ice Cream'),
       ('Feta Cheese'),
       ('Cream Cheese'),
       ('Mozzarella'),
       ('Provolone'),
       ('Gouda'),
       ('Pork'),
       ('Veal'),
       ('Chicken'),
       ('Beef'),
       ('Lamb'),
       ('Turkey'),
       ('Duck'),
       ('Salami'),
       ('Sausage'),
       ('Bacon'),
       ('Ham'),
       ('Pepperoni'),
       ('Chorizo'),
       ('Pastrami'),
       ('Ground Beef'),
       ('Anchovies'),
       ('Caviar'),
       ('Crab sticks'),
       ('Shrimps'),
       ('Mussels'),
       ('Fish'),
       ('Oysters'),
       ('Hercules'),
       ('Buckwheat'),
       ('Semolina'),
       ('Pearl barley'),
       ('Barley groats'),
       ('Millet'),
       ('Rice'),
       ('Sago'),
       ('Lentils'),
       ('Noodles'),
       ('Pasta'),
       ('Potato flour'),
       ('Wheat flour'),
       ('Bread'),
       ('Wine'),
       ('Vodka'),
       ('Cognac'),
       ('Liquor'),
       ('Beer'),
       ('Mushrooms'),
       ('Yeast'),
       ('Cocoa'),
       ('Coffee'),
       ('Poppy'),
       ('Vegetable oil'),
       ('Honey'),
       ('Sugar'),
       ('Soda'),
       ('Tea'),
       ('Chocolate'),
       ('Eggs');

INSERT INTO public.meal (meal_name)
VALUES ('Breakfast'),
       ('Lunch'),
       ('Dinner'),
       ('Desserts'),
       ('Snacks');


INSERT INTO public.recipes (recipe_name, recipe_description, meal_id)
VALUES ('Cheerful hunter', '1 cup Anchovies
2 tablespoons organic Tomato
1 tablespoon Apple
½ teaspoon Mozzarella
1 cup Hercules
1 tablespoon Vegetable oil
1 teaspoon Bread
1 teaspoon Rice
Vodka to serve

Preparation:
In a medium bowl, add the Anchovies, Tomato, Apple, Mozzarella to combine.
In a medium bowl or liquid measuring cup, add Hercules, Vegetable oil, Rice and Bread to combine.
Pour the liquid mixture into the dry mixture and whisk until smooth.
Let batter rest for 5 minutes.
Pour about ½ cup (65 grams) of batter onto a nonstick pan or griddle over medium heat.
When the top begins to bubble, flip the pancake and cook until golden.
Serve warm with Vodka.
Enjoy!', 3),
       ('Grilled Vegetable Medley',
        'A delightful combination of grilled Eggplant, Tomato, Zucchini, Bell Pepper, and Asparagus, seasoned with herbs and served as a healthy side dish.',
        2),
       ('Creamy Potato Salad',
        'A classic Potato Salad recipe with a creamy twist. Tender Potatoes, diced Onion, and crunchy Cucumber tossed in a rich Sour cream and Mayonnaise dressing.',
        2),
       ('Fruit Salad Delight',
        'A refreshing medley of Apricot, Pear, Apple, Grape, Orange, Banana, and Strawberry, dressed with a tangy Kiwi and Pineapple sauce, perfect for a summer treat.',
        2),
       ('Cheesy Broccoli Bake',
        'A cheesy and comforting casserole made with Broccoli florets, creamy Cheese sauce, and a crispy Bread crumb topping. Baked to golden perfection.',
        2),
       ('Lemony Chicken Piccata',
        'Succulent Chicken breasts cooked in a zesty Lemon and Capers sauce, served over a bed of fluffy Hercules or Rice. A flavorful and satisfying main course.',
        2),
       ('Creamy Mushroom Pasta',
        'A velvety pasta dish featuring sautéed Mushrooms, Garlic, and Thyme, combined with a creamy sauce made of Butter, Cream, and Parmesan Cheese.',
        2),
       ('Sweet and Spicy Glazed Ham',
        'A show-stopping centerpiece for special occasions. A succulent Ham coated with a sweet and spicy glaze made of Honey, Brown Sugar, Mustard, and a hint of Cinnamon.',
        2),
       ('Seafood Paella',
        'A vibrant Spanish rice dish with a variety of seafood including Shrimps, Mussels, and Fish, cooked with aromatic Saffron, Bell Pepper, and Tomato.',
        2),
       ('Creamy Spinach Dip',
        'A creamy and cheesy Spinach dip made with Spinach, Cream Cheese, Sour cream, and a blend of savory spices. Perfect for parties and gatherings.',
        2),
       ('Roasted Cauliflower with Garlic and Parmesan',
        'Tender Roasted Cauliflower florets tossed in a garlic-infused Olive oil and sprinkled with grated Parmesan Cheese. A flavorful and healthy side dish.',
        2),
       ('Stuffed Bell Peppers',
        'Colorful Bell Peppers stuffed with a savory mixture of ground Beef, Rice, Onion, and spices. Baked until tender and topped with melted Cheese.',
        2),
       ('Mango Salsa Chicken',
        'Grilled Chicken breasts topped with a refreshing Mango salsa made with ripe Mango, Red Onion, Cilantro, Lime juice, and a hint of Jalapeno.',
        2),
       ('Creamy Garlic Shrimp Pasta',
        'Succulent Shrimp cooked in a creamy Garlic sauce and served over a bed of al dente Pasta. A luxurious and satisfying seafood pasta dish.',
        2),
       ('Honey Glazed Carrots',
        'Tender Carrots cooked in a sweet and sticky glaze made with Honey, Butter, and a touch of Cinnamon. An irresistible side dish for any meal.',
        2),
       ('Blueberry Pancakes',
        'Fluffy Pancakes studded with juicy Blueberries and served with a drizzle of Maple syrup. A delicious and indulgent breakfast treat.',
        2),
       ('Apple Cinnamon Muffins',
        'Moist and flavorful Apple Cinnamon Muffins packed with chunks of fresh Apple and a hint of warm Cinnamon. Perfect for a quick and tasty snack.',
        2),
       ('Lemon Garlic Butter Salmon',
        'Pan-seared Salmon fillets glazed with a tangy Lemon Garlic Butter sauce. Served with a side of steamed Asparagus or Roasted Potatoes.',
        2),
       ('Beef Stir-Fry with Vegetables',
        'Tender strips of Beef cooked with a colorful assortment of stir-fried Vegetables, flavored with a savory sauce and served over Rice or Noodles.',
        2),
       ('Caprese Salad',
        'A simple and elegant salad made with ripe Tomatoes, fresh Mozzarella Cheese, and fragrant Basil leaves, drizzled with Balsamic glaze.',
        2),
       ('Greek Salad',
        'A refreshing and vibrant salad featuring crisp Lettuce, juicy Tomatoes, Cucumber, Kalamata Olives, Feta Cheese, and a zesty Lemon dressing.',
        2),
       ('Garlic Butter Steak',
        'Juicy and flavorful Steak cooked to perfection in a sizzling Garlic Butter sauce. Served with a side of roasted Potatoes or a fresh Salad.',
        2),
       ('Creamy Mushroom Soup',
        'A rich and velvety Mushroom soup made with sautéed Mushrooms, Onions, Garlic, and a touch of Cream. Perfect for a cozy and comforting meal.',
        2),
       ('Spinach and Feta Stuffed Chicken Breast',
        'Tender Chicken breasts stuffed with a delicious filling of wilted Spinach, tangy Feta Cheese, and aromatic Herbs. Baked until golden and juicy.',
        2),
       ('Strawberry Shortcake',
        'A classic dessert made with layers of fluffy shortcake, fresh Strawberries, and whipped Cream. A delightful sweet treat for any occasion.',
        2),
       ('Roasted Vegetable Quinoa Salad',
        'Nutritious Quinoa combined with roasted Eggplant, Zucchini, Bell Pepper, and Red Onion, dressed with a lemony vinaigrette. A hearty and healthy salad.',
        2),
       ('Creamy Garlic Parmesan Pasta',
        'A decadent pasta dish with al dente Pasta coated in a creamy Garlic Parmesan sauce, garnished with fresh Parsley. A comforting and satisfying meal.',
        2),
       ('Teriyaki Chicken Stir-Fry',
        'Tender pieces of Chicken stir-fried with colorful Vegetables in a savory Teriyaki sauce. Served over steamed Rice or Noodles.',
        2),
       ('Mediterranean Hummus',
        'A creamy and flavorful dip made with Chickpeas, Garlic, Lemon juice, and Olive oil. Served with pita bread or fresh Vegetable sticks.',
        2),
       ('Lemon Poppy Seed Muffins',
        'Moist and fluffy Lemon-flavored muffins with a delightful crunch from poppy seeds. Perfect for a breakfast on-the-go or a sweet snack.',
        2),
       ('Garlic Butter Shrimp Scampi',
        'Succulent Shrimp sautéed in a garlic-infused Butter sauce, finished with a splash of white Wine and served over a bed of Linguine. A classic seafood dish with a rich and buttery flavor.',
        2),
       ('Stuffed Eggplant Parmesan',
        'Tender roasted Eggplant halves filled with a savory mixture of Tomato, Onion, Garlic, and herbs. Topped with melted Mozzarella and Parmesan Cheese, then baked to perfection.',
        2),
       ('Thai Red Curry with Chicken',
        'A fragrant and spicy Thai curry made with tender Chicken, Coconut Milk, Red Curry paste, and an assortment of colorful Vegetables. Serve with steamed Jasmine Rice for a satisfying meal.',
        2),
       ('Creamy Spinach and Artichoke Dip',
        ' A creamy and indulgent dip made with Spinach, Artichoke hearts, Cream Cheese, Sour cream, and a blend of melted Cheeses. Perfect for parties or game day snacking.',
        2),
       ('Roasted Vegetable Frittata',
        'A hearty and flavorful frittata loaded with roasted Vegetables such as Bell Peppers, Zucchini, Onion, and Spinach. Baked with Eggs and Cheese for a satisfying brunch or dinner.',
        2),
       ('Cucumber and Tomato Salad',
        'A refreshing salad featuring crisp Cucumber slices, juicy Tomato chunks, Red Onion, and fresh Herbs. Tossed with a tangy vinaigrette dressing for a light and healthy side dish.',
        2),
       ('Honey Glazed Salmon',
        'Tender and flaky Salmon fillets coated in a sweet and sticky Honey glaze. Baked or grilled to perfection, this dish pairs well with steamed Vegetables or a fresh Salad.',
        2),
       ('Mediterranean Couscous Salad',
        ' A vibrant and flavorful salad made with fluffy Couscous, colorful Cherry Tomatoes, Cucumber, Kalamata Olives, Feta Cheese, and a zesty Lemon dressing. Perfect for picnics or potlucks.',
        2),
       ('Italian Sausage and Peppers',
        'Sautéed Italian Sausages with colorful Bell Peppers and Onions, seasoned with Italian herbs and spices. Serve on a crusty roll or over Pasta for a hearty and satisfying meal.',
        2),
       ('Chicken Caesar Salad',
        ' Crisp Romaine Lettuce tossed with grilled Chicken, Parmesan Cheese, Homemade Croutons, and a creamy Caesar dressing. A classic salad that is both satisfying and delicious.',
        2),
       ('Teriyaki Glazed Beef Skewers',
        'Tender pieces of Beef marinated in a flavorful Teriyaki sauce, threaded onto skewers, and grilled to perfection. Served with a side of steamed Rice or Asian-style Slaw.',
        2),
       ('Spinach and Cheese Stuffed Mushrooms',
        'Button Mushrooms filled with a creamy mixture of Spinach, Cheese, Garlic, and herbs, then baked until golden and bubbly. An elegant appetizer or party snack.',
        2),
       ('Lemon Herb Roasted Chicken',
        'A juicy and flavorful Roasted Chicken infused with the bright flavors of Lemon, Garlic, and fresh Herbs. Serve with roasted Potatoes and steamed Vegetables for a comforting meal.',
        2),
       ('Caprese Stuffed Chicken',
        'Tender Chicken breasts stuffed with Mozzarella Cheese, Basil leaves, and Sun-dried Tomatoes, then baked to perfection. Serve with a side of roasted Vegetables or a fresh Salad.',
        2),
       ('Zucchini Noodles with Pesto',
        'Spiralized Zucchini sautéed in a homemade Pesto sauce, garnished with Cherry Tomatoes and Parmesan Cheese. A light and nutritious alternative to traditional Pasta dishes.',
        2),
       ('Honey Mustard Chicken Salad',
        'Grilled or roasted Chicken breast slices served on a bed of mixed Greens, with Cherry Tomatoes, Cucumber, and Avocado. Drizzled with a tangy Honey Mustard dressing.',
        2),
       ('Roasted Garlic Mashed Potatoes',
        'Creamy and flavorful Mashed Potatoes made with roasted Garlic, Butter, and a hint of fresh Herbs. The perfect side dish for roasted Meats or poultry.',
        2),
       ('Veggie Spring Rolls with Peanut Sauce',
        'Fresh and crispy Spring Rolls filled with a colorful medley of julienned Vegetables, served with a creamy Peanut dipping sauce. A light and satisfying appetizer or snack.',
        2),
       (' Greek Lemon Chicken Soup',
        'A comforting and tangy soup made with tender Chicken, Rice, fresh Lemon juice, and fragrant Herbs. Serve with crusty Bread for a hearty meal.',
        2),
       ('Blueberry Pancakes with Maple Syrup',
        'Fluffy and golden Pancakes studded with juicy Blueberries and drizzled with sweet Maple Syrup. A delightful breakfast or brunch option that will satisfy your sweet cravings.',
        2),
       ('Creamy Tomato Basil Soup',
        'A comforting and velvety Tomato soup infused with aromatic Basil leaves and a touch of Cream. Perfect for chilly days, especially when served with a grilled Cheese sandwich.',
        2),
       ('Balsamic Glazed Roasted Vegetables',
        ' Assorted Vegetables such as Eggplant, Bell Peppers, Zucchini, and Onion, roasted to perfection and glazed with a tangy Balsamic reduction. A colorful and flavorful side dish.',
        2),
       ('Mediterranean Stuffed Peppers',
        'Colorful Bell Peppers filled with a Mediterranean-inspired mixture of Rice, Tomatoes, Olives, and Feta Cheese. Baked until tender and topped with fresh Herbs.',
        2),
       ('Chicken Alfredo Pasta',
        'Tender Chicken breast slices served over a bed of fettuccine Pasta, coated in a creamy Alfredo sauce and garnished with grated Parmesan Cheese. A classic Italian dish that is sure to please.',
        2),
       ('Grilled Pineapple Chicken Skewers',
        'Succulent pieces of marinated Chicken and sweet Pineapple chunks threaded onto skewers and grilled to perfection. Served with a side of Coconut Rice or a fresh Salad.',
        2),
       ('Creamy Garlic Mashed Cauliflower',
        'A low-carb and healthier alternative to traditional Mashed Potatoes. Steamed Cauliflower blended with Garlic, Butter, and Cream for a creamy and flavorful side dish.',
        2),
       ('Mango Salsa',
        'A vibrant and refreshing salsa made with ripe Mangoes, diced Bell Peppers, Red Onion, Lime juice, and fresh Cilantro. Perfect as a topping for grilled Fish or Chicken.',
        2),
       ('Honey Sesame Chicken',
        'Crispy and tender Chicken pieces tossed in a sticky Honey Sesame sauce, garnished with toasted Sesame seeds and Green Onions. Serve over steamed Rice for a delicious Asian-inspired meal.',
        2),
       ('Caramelized Onion and Goat Cheese Tart',
        'A savory tart with a buttery and flaky crust, topped with caramelized Onions, creamy Goat Cheese, and a sprinkle of fresh Thyme. Perfect for brunch or as an appetizer.',
        2),
       ('Strawberry Spinach Salad',
        'Fresh Spinach leaves topped with sweet Strawberries, Red Onion slices, crunchy Almonds, and crumbled Feta Cheese. Tossed with a tangy Balsamic vinaigrette for a light and refreshing salad.',
        2),
       ('Coconut Curry Shrimp',
        'Succulent Shrimp cooked in a fragrant and creamy Coconut Curry sauce, infused with aromatic Spices and served over steamed Rice. A flavorful and satisfying seafood dish.',
        2),
       ('Roasted Red Pepper and Tomato Soup',
        'A velvety and flavorful soup made with roasted Red Peppers, Tomatoes, Garlic, and aromatic Herbs. Garnished with a drizzle of Olive Oil and fresh Basil leaves.',
        2),
       ('BBQ Pulled Pork Sandwiches',
        ' Slow-cooked and tender Pulled Pork tossed in a tangy and smoky BBQ sauce, served on a toasted bun with a side of Coleslaw. A classic comfort food option for barbecue lovers.',
        2),
       ('Teriyaki Glazed Salmon',
        ' Tender Salmon fillets glazed with a sweet and savory Teriyaki sauce, garnished with Sesame seeds and sliced Green Onions. Baked or grilled to perfection, this dish is a crowd-pleaser.',
        2),
       ('Quinoa Salad with Roasted Vegetables',
        'Nutty and nutritious Quinoa mixed with roasted Vegetables like Eggplant, Zucchini, Bell Peppers, and Red Onion. Tossed with a zesty Lemon dressing and sprinkled with fresh Herbs.',
        2),
       ('Blueberry Lemon Loaf',
        'A moist and flavorful Lemon-infused loaf cake studded with juicy Blueberries and topped with a tangy Lemon glaze. A delightful dessert or afternoon treat.',
        2),
       ('Garlic Herb Roasted Potatoes',
        'Baby Potatoes tossed in a mixture of Garlic, fresh Herbs, and Olive Oil, then roasted until crispy and golden. An irresistible side dish that pairs well with any protein.',
        2),
       ('Italian Meatball Subs',
        ' Homemade Meatballs made with a combination of Beef and Pork, simmered in a rich Tomato sauce, then served on a toasted Baguette with melted Cheese. A satisfying and classic sandwich option.',
        2),
       ('Chicken and Vegetable Stir-Fry',
        'Tender Chicken breast strips sautéed with an assortment of colorful Vegetables, tossed in a savory Stir-Fry sauce and served over steamed Rice or Noodles. Quick, healthy, and packed with flavors.',
        2),
       ('Apple Cinnamon Pancakes',
        'Fluffy Pancakes infused with warm Cinnamon and filled with chunks of fresh Apple. Drizzled with Maple Syrup and sprinkled with a dash of Cinnamon sugar for an indulgent breakfast treat.',
        2),
       ('Greek Gyro Salad',
        ' A deconstructed version of the popular Greek Gyro sandwich, featuring tender slices of seasoned Meat (Lamb, Chicken, or Beef), served over a bed of Lettuce, Tomatoes, Cucumber, Red Onion, and Tzatziki sauce.',
        2),
       ('Honey Roasted Carrots and Parsnips',
        'Sweet and savory roasted Carrots and Parsnips glazed with Honey, Olive Oil, and a sprinkle of fresh Herbs. A colorful and flavorful side dish that complements any meal.',
        2),
       ('Baked Zucchini Fries',
        'Crispy and seasoned Zucchini sticks coated in breadcrumbs, baked until golden and served with a tangy Marinara sauce. A healthier alternative to traditional French fries.',
        2),
       ('Mexican Chicken Enchiladas',
        ' Shredded Chicken mixed with spices, rolled in Corn Tortillas, and topped with a zesty Enchilada sauce and melted Cheese. Baked until bubbly and served with Rice and Beans.',
        2),
       ('Lemon Herb Grilled ',
        'Assorted Vegetables such as Bell Peppers, Zucchini, Eggplant, and Asparagus marinated in a tangy Lemon-Herb dressing, then grilled to perfection. A flavorful and healthy side dish.',
        2),
       ('Maple Glazed Bacon-Wrapped Dates',
        'Sweet and salty appetizers made by stuffing Dates with creamy Goat Cheese, wrapping them in smoky Bacon, and baking until crispy. Drizzled with Maple syrup for a delightful flavor contrast.',
        2),
       ('Sausage and Mushroom Pizza',
        'Thin and crispy Pizza crust topped with savory Sausage, sautéed Mushrooms, Mozzarella Cheese, and a sprinkle of fresh Herbs. A homemade pizza that will satisfy your cravings.',
        2),
       ('Baked Stuffed Apples',
        ' Fresh Apples cored and stuffed with a mixture of Oats, Cinnamon, Honey, and chopped Nuts. Baked until tender and served with a scoop of Vanilla Ice Cream or a dollop of Whipped Cream.',
        2),
       ('Cabbage Roll Casserole',
        'All the flavors of traditional Cabbage rolls in an easy-to-make casserole form. Layers of seasoned Ground Beef, Rice, and Cabbage leaves, baked in a rich Tomato sauce until bubbly and delicious.',
        2),
       ('Mediterranean Grilled Chicken Skewers',
        'Tender pieces of marinated Chicken threaded onto skewers, grilled to perfection, and served with a side of Tzatziki sauce and a fresh Greek Salad. A flavorful and healthy meal option.',
        2),
       ('Chocolate Chip Banana Bread',
        'Moist and flavorful Banana Bread studded with chunks of Chocolate, perfect for a quick breakfast or a sweet treat. Best enjoyed warm with a spread of Butter.',
        2),
       ('Creamy Tuscan Shrimp Pasta',
        'Succulent Shrimp cooked in a creamy sauce made with Sun-dried Tomatoes, Spinach, Garlic, and Parmesan Cheese. Tossed with your favorite Pasta for a decadent and satisfying meal.',
        2),
       ('Honey Glazed Chicken Drumsticks',
        'Tender and juicy Chicken Drumsticks coated in a sweet and sticky Honey glaze, seasoned with a blend of herbs and spices. Baked until golden and served with a side of roasted Vegetables.',
        2),
       ('Caprese Salad Skewers',
        'Skewers featuring Cherry Tomatoes, fresh Mozzarella Cheese, and Basil leaves, drizzled with Balsamic glaze. A colorful and bite-sized appetizer that showcases the classic Caprese flavors.',
        2),
       ('Sweet and Sour Pork Stir-Fry',
        'Tender Pork slices stir-fried with colorful Bell Peppers, Pineapple chunks, and a tangy Sweet and Sour sauce. Serve over steamed Rice or Noodles for a delicious Asian-inspired meal.',
        2),
       ('Creamy Broccoli and Cheddar Soup',
        'A comforting and velvety soup made with fresh Broccoli florets, Cheddar Cheese, and a touch of Cream. Perfect for chilly days, especially when served with crusty Bread.',
        2),
       ('Mediterranean Quinoa Stuffed Bell Peppers',
        'Bell Peppers stuffed with a mixture of cooked Quinoa, Tomatoes, Olives, Feta Cheese, and Mediterranean spices. Baked until tender and served as a flavorful and nutritious vegetarian meal option.',
        2),
       ('Stuffed Mushroom Caps',
        'Mushroom caps filled with a savory mixture of sautéed Garlic, Spinach, Parmesan Cheese, and Breadcrumbs. Baked until golden and served as a delightful appetizer or side dish.',
        2),
       ('Greek Style Lamb Kebabs',
        'Tender chunks of marinated Lamb skewered with colorful Bell Peppers, Onions, and Cherry Tomatoes. Grilled to perfection and served with Tzatziki sauce and warm Pita bread.',
        2),
       ('Grilled Chicken Caesar Salad',
        'Grilled Chicken breast served on a bed of fresh Romaine lettuce, tossed with Caesar dressing, Parmesan Cheese, and crunchy Croutons. A classic and satisfying salad option.',
        2),
       ('Spicy Thai Basil Beef Stir-Fry',
        'Thinly sliced Beef stir-fried with aromatic Basil leaves, Bell Peppers, and Thai spices for a flavorful and spicy dish. Served over steamed Jasmine Rice for a complete meal.',
        2),
       ('Caprese Stuffed Chicken Breast',
        'Chicken breast stuffed with Mozzarella Cheese, Sun-dried Tomatoes, and fresh Basil, then baked until juicy and tender. Served with a side of roasted Potatoes or a fresh Salad.',
        2),
       ('Chocolate Raspberry Tart',
        ' A decadent Chocolate tart filled with a luscious Raspberry filling, topped with fresh Raspberries and a dusting of powdered Sugar. A delightful dessert for special occasions.',
        2),
       ('Grilled Vegetable Wrap',
        'Grilled Eggplant, Zucchini, Bell Peppers, and Onion wrapped in a soft Tortilla with Hummus, Feta Cheese, and fresh Greens. A flavorful and satisfying vegetarian wrap option.',
        2),
       ('Baked Garlic Parmesan Shrimp',
        'Succulent Shrimp baked in a garlic-infused Parmesan breadcrumb coating, served with a squeeze of fresh Lemon. An easy and delicious appetizer or light meal option.',
        2),
       ('Thai Green Curry with Vegetables',
        'A fragrant and spicy Thai Green Curry made with an assortment of fresh Vegetables, Coconut Milk, and Thai Green Curry paste. Served over steamed Jasmine Rice for a flavorful and satisfying meal.',
        2),
       ('Maple Glazed Salmon with Roasted Vegetables',
        'Maple-glazed Salmon fillets served with a side of roasted seasonal Vegetables. The combination of sweet and savory flavors makes this dish a crowd-pleaser.',
        2),
       ('Quinoa and Black Bean Stuffed Peppers',
        'Colorful Bell Peppers stuffed with a mixture of cooked Quinoa, Black Beans, Corn, Tomatoes, and Mexican spices. Baked until tender and served with a dollop of Guacamole or Sour Cream.',
        2),
       ('Lemon Garlic Roasted Chicken Thighs',
        'Tender and juicy Chicken thighs marinated in a tangy Lemon Garlic mixture, then roasted until golden and flavorful. Serve with a side of roasted Potatoes and steamed Green Beans.',
        2),
       ('Berry Smoothie Bowl',
        'A refreshing and nutritious smoothie bowl made with a blend of mixed Berries, Banana, Greek Yogurt, and a variety of toppings such as Granola, Chia seeds, and fresh Berries.',
        2),
       ('Honey Mustard Glazed Chicken Skewers',
        'Tender Chicken pieces marinated in a tangy Honey Mustard sauce, threaded onto skewers, and grilled to perfection. Served with a side of Rice or a fresh Salad.',
        2),
       ('Beef and Broccoli Stir-Fry',
        'Thinly sliced Beef cooked with crisp Broccoli florets in a savory stir-fry sauce. Served over steamed Rice or Noodles for a quick and delicious meal.',
        2),
       ('Mediterranean Chickpea Salad',
        'A vibrant and refreshing salad made with Chickpeas, Cherry Tomatoes, Cucumber, Red Onion, Feta Cheese, and a tangy Lemon Herb dressing. Perfect as a light lunch or a side dish.',
        2),
       ('Baked Apple Crisp',
        'Sliced Apples baked with a buttery and cinnamon-infused crumb topping until golden and bubbly. Serve warm with a scoop of Vanilla Ice Cream for a delightful dessert.',
        2),
       ('Hawaiian Chicken Kabobs',
        'Grilled Chicken skewers with a tropical twist, featuring chunks of marinated Chicken, Pineapple, Bell Peppers, and Red Onion. Served with a side of Coconut Rice for a taste of the islands.',
        2),
       ('Mexican Street Corn Salad',
        'A refreshing and flavorful salad made with grilled Corn kernels, Cotija Cheese, Lime juice, and a combination of spices. A popular Mexican street food-inspired side dish.',
        2),
       ('Lemon Herb Roasted Vegetables',
        'Assorted Vegetables such as Carrots, Potatoes, Zucchini, and Bell Peppers tossed in a tangy Lemon Herb marinade, then roasted to perfection. A versatile and healthy side dish.',
        2),
       ('Creamy Chicken Alfredo Pasta',
        'Tender Chicken breast pieces served with a creamy Alfredo sauce and tossed with Fettuccine Pasta. A classic Italian dish that is rich, comforting, and satisfying.',
        2),
       ('Grilled Pineapple and Shrimp Skewers',
        'Juicy Pineapple chunks and succulent Shrimp threaded onto skewers, grilled to perfection, and served with a zesty Mango Salsa. A tropical and delicious appetizer or main course option.',
        2),
       ('Caprese Stuffed Portobello Mushrooms',
        'Portobello Mushrooms stuffed with a mixture of Mozzarella Cheese, Cherry Tomatoes, fresh Basil, and Balsamic glaze. Baked until the mushrooms are tender and the cheese is melty. A flavorful vegetarian dish.',
        2),
       ('Creamy Garlic Parmesan Mashed Potatoes',
        'Fluffy and creamy Mashed Potatoes blended with Garlic, Parmesan Cheese, and Butter. A comforting and indulgent side dish that pairs well with a variety of main courses.',
        2),
       ('Chicken Tortilla Soup',
        'A hearty and flavorful soup made with shredded Chicken, Tomatoes, Black Beans, Corn, and a variety of spices. Topped with crispy Tortilla strips, Avocado, and fresh Cilantro.',
        2),
       ('Ratatouille',
        'A traditional French dish made with a medley of Eggplant, Zucchini, Bell Peppers, Onion, and Tomato, cooked with herbs and aromatic spices. Serve as a main course or a side dish.',
        2),
       ('Honey Soy Glazed Salmon',
        'Salmon fillets glazed with a sweet and savory Honey Soy sauce, broiled until caramelized and flaky. Serve with a side of steamed Rice and steamed Vegetables for a wholesome meal.',
        2),
       ('Stuffed Bell Peppers with Quinoa and Vegetables',
        'Colorful Bell Peppers stuffed with a filling of cooked Quinoa, sautéed Vegetables, and melted Cheese. Baked until the peppers are tender and the filling is heated through.',
        2),
       ('Chocolate Chip Cookies',
        'Classic homemade Chocolate Chip Cookies made with butter, Brown Sugar, and plenty of Chocolate chips. Soft and chewy on the inside with a slightly crispy edge.',
        2),
       ('Chicken Caesar Wraps',
        'Grilled Chicken breast, Romaine lettuce, Parmesan Cheese, and Caesar dressing wrapped in a soft Tortilla. A quick and easy lunch or dinner option.',
        2),
       ('Mushroom Risotto',
        'Creamy and flavorful Mushroom Risotto made with Arborio Rice, sautéed Mushrooms, Parmesan Cheese, and a hint of White Wine. A comforting and elegant Italian dish.',
        2),
       ('Spinach and Feta Stuffed Portobello Mushrooms',
        'Portobello Mushrooms filled with a mixture of wilted Spinach, crumbled Feta Cheese, Garlic, and breadcrumbs. Baked until the mushrooms are tender and the filling is golden.',
        2),
       ('Baked Honey Mustard Chicken Thighs',
        'Chicken thighs marinated in a tangy Honey Mustard mixture, baked until golden and juicy. Serve with a side of roasted Vegetables or a fresh Salad.',
        2),
       ('Roasted Garlic Mashed Cauliflower',
        'A healthier alternative to traditional Mashed Potatoes, this recipe features roasted Garlic-infused Cauliflower blended with Butter, Cream, and seasonings. Creamy and delicious.',
        2),
       ('Beef Stir-Fry with Noodles',
        'Tender strips of Beef sautéed with colorful Vegetables and tossed with cooked Noodles in a flavorful sauce. Quick and satisfying for a weeknight dinner.',
        2),
       ('Greek Salad with Grilled Chicken',
        'A refreshing and healthy salad made with crisp Lettuce, juicy Tomatoes, Cucumber, Kalamata Olives, Feta Cheese, and Grilled Chicken. Tossed with a tangy Greek dressing.',
        2),
       ('Cinnamon Apple Pancakes',
        'Fluffy Pancakes infused with Cinnamon and filled with tender Apple slices. Drizzle with Maple syrup and sprinkle with powdered Sugar for a cozy breakfast treat.',
        2),
       ('Shrimp and Avocado Salad',
        'A light and refreshing salad featuring chilled Shrimp, creamy Avocado, Cherry Tomatoes, Cucumber, and mixed Greens. Tossed with a zesty Citrus dressing.',
        2),
       ('Spaghetti Carbonara',
        'Classic Italian Pasta dish made with Spaghetti, crispy Bacon, Parmesan Cheese, Eggs, and Black Pepper. Creamy, rich, and packed with flavor.',
        2),
       ('Honey Sesame Chicken Stir-Fry',
        'Tender Chicken pieces stir-fried with colorful Vegetables in a sweet and savory Honey Sesame sauce. Serve over steamed Rice for a satisfying meal.',
        2),
       ('Caprese Stuffed Avocado',
        'Ripe Avocado halves filled with a mixture of diced Tomatoes, fresh Mozzarella Cheese, and Basil, drizzled with Balsamic glaze. A healthy and flavorful appetizer or light meal.',
        2),
       ('Maple Roasted Butternut Squash',
        'Butternut Squash cubes roasted with Maple syrup, Cinnamon, and a touch of Butter until caramelized and tender. A delicious side dish for the fall season.',
        2),
       ('Chicken Fajitas',
        'Sautéed Chicken strips with colorful Bell Peppers and Onions, seasoned with Fajita spices, and served with warm Tortillas, Guacamole, and Salsa.',
        2),
       ('Roasted Beet and Goat Cheese Salad',
        'Roasted Beet slices served on a bed of mixed Greens, topped with crumbled Goat Cheese, toasted Walnuts, and a drizzle of Balsamic vinaigrette. A vibrant and flavorful salad.',
        2),
       ('Baked Teriyaki Chicken Wings',
        'Tender Chicken wings baked in a sticky and flavorful Teriyaki sauce until caramelized and irresistible. Perfect for game day or as a party appetizer.',
        2),
       ('Zucchini Noodles with Pesto Sauce',
        'Spiralized Zucchini noodles sautéed with homemade Pesto sauce, Cherry Tomatoes, and grated Parmesan Cheese. A light and healthy alternative to traditional pasta.',
        2),
       ('Beef Tacos with Fresh Salsa',
        'Seasoned Ground Beef cooked to perfection and served in warm Tortillas with a fresh Tomato and Onion salsa, shredded Lettuce, and a squeeze of Lime juice.',
        2),
       ('Lemon Herb Grilled Chicken',
        'Tender Chicken marinated in a zesty Lemon Herb mixture, then grilled to juicy perfection. Serve with a side of Grilled Vegetables or a fresh Salad.',
        2),
       ('Garlic Roasted Asparagus',
        'Fresh Asparagus spears tossed in Olive Oil, Garlic, and a pinch of Salt, then roasted until tender and slightly caramelized. A simple and nutritious side dish.',
        2),
       ('Mediterranean Quinoa Salad',
        'A vibrant salad featuring cooked Quinoa, chopped Cucumber, Cherry Tomatoes, Kalamata Olives, crumbled Feta Cheese, and a zesty Lemon-herb dressing. Fresh and satisfying.',
        2),
       ('Grilled Salmon with Dill Sauce',
        'Grilled Salmon fillets seasoned with Salt, Pepper, and fresh Dill, served with a creamy and tangy Dill Sauce. A healthy and delicious seafood option.',
        2),
       ('Caprese Pasta Salad',
        'A refreshing pasta salad made with cooked Rotini pasta, fresh Mozzarella balls, Cherry Tomatoes, Basil leaves, and a tangy Balsamic vinaigrette. Perfect for picnics and potlucks.',
        2),
       ('Teriyaki Salmon with Stir-Fried Vegetables',
        'Grilled Salmon fillets glazed with a homemade Teriyaki sauce, served with a medley of sautéed Vegetables including Broccoli, Carrots, and Bell Peppers. A nutritious and flavorful meal.',
        2),
       ('Apple Cinnamon French Toast',
        'Thick slices of French Toast soaked in a mixture of beaten Eggs, Milk, Cinnamon, and Vanilla, topped with caramelized Apple slices and a dusting of powdered Sugar. A breakfast delight.',
        2),
       ('Greek Gyro Wraps',
        'Tender strips of marinated Chicken or Lamb, grilled to perfection and wrapped in warm Pita bread with Tzatziki sauce, Lettuce, Tomato, Onion, and a sprinkle of Feta Cheese. A flavorful and satisfying Greek-inspired dish.',
        2),
       ('Lemon Garlic Shrimp Pasta',
        'Succulent Shrimp sautéed in a garlic and lemon-infused Butter sauce, tossed with cooked Pasta and fresh Parsley. A quick and delicious seafood pasta dish.',
        2),
       ('Stuffed Mushrooms with Cream Cheese and Spinach',
        'Mushroom caps filled with a creamy mixture of Spinach, Cream Cheese, Garlic, and Parmesan Cheese, baked until golden and bubbly. A tasty appetizer or side dish.',
        2),
       ('Apple Walnut Salad with Maple Vinaigrette',
        'Crisp Lettuce greens tossed with sliced Apples, toasted Walnuts, crumbled Blue Cheese, and a sweet Maple Vinaigrette dressing. A refreshing and autumn-inspired salad.',
        2),
       ('Mediterranean Chicken Skewers',
        'Marinated Chicken chunks threaded onto skewers with colorful Vegetables like Cherry Tomatoes, Red Onion, and Zucchini, grilled to perfection and served with a tangy Yogurt sauce. A flavorful and protein-packed meal.',
        2),
       (' Beef and Broccoli Stir-Fry',
        'Thinly sliced Beef cooked with Broccoli florets in a savory sauce made of Soy sauce, Garlic, Ginger, and a touch of Honey. Serve over steamed Rice for a quick and satisfying stir-fry.',
        2),
       ('Honey Lime Grilled Chicken',
        'Juicy Chicken breasts marinated in a mixture of Honey, Lime juice, Garlic, and spices, then grilled to perfection. Serve with a side of grilled Vegetables for a healthy and flavorful meal.',
        2),
       ('Caprese Quinoa Stuffed Tomatoes',
        'Fresh Tomatoes hollowed out and filled with a mixture of cooked Quinoa, diced Mozzarella, fresh Basil, and Balsamic glaze. Baked until the Cheese melts and the flavors meld together. A light and satisfying vegetarian dish.',
        2),
       ('Thai Green Curry with Shrimp',
        'A fragrant and spicy Thai curry made with Coconut milk, Green Curry paste, Shrimp, and an assortment of Vegetables such as Bell Peppers, Bamboo shoots, and Snow Peas. Serve over steamed Jasmine Rice for a taste of Thailand.',
        2),
       ('Honey Soy Glazed Pork Chops',
        'Thick-cut Pork chops marinated in a sweet and savory Honey Soy sauce, then grilled or pan-seared to perfection. Serve with steamed Vegetables and Rice for a delicious and satisfying meal.',
        2),
       ('Beef and Vegetable Stir-Fry',
        'Thinly sliced Beef cooked with a colorful mix of Vegetables, such as Broccoli, Carrots, Bell Peppers, and Snap Peas, in a savory sauce. Quick, easy, and full of flavor.',
        2),
       ('Creamy Garlic Parmesan Chicken',
        'Tender Chicken breasts coated in a creamy Garlic Parmesan sauce, served over a bed of Pasta or Mashed Potatoes. A comforting and satisfying main course.',
        2),
       ('Raspberry White Chocolate Cheesecake Bars',
        'Rich and creamy Cheesecake bars with a buttery Graham cracker crust, swirled with tangy Raspberry sauce and studded with white Chocolate chunks. A decadent dessert for special occasions.',
        2),
       ('Teriyaki Vegetable Stir-Fry',
        'A colorful and nutritious stir-fry featuring a variety of Vegetables like Broccoli, Snap Peas, Carrots, Bell Peppers, and Water Chestnuts, tossed in a homemade Teriyaki sauce. Serve over steamed Rice or Noodles for a satisfying vegetarian meal.',
        2),
       ('Lemon Raspberry Tart',
        'A buttery Tart crust filled with a tangy Lemon curd filling and topped with fresh Raspberries. A delightful dessert that balances sweetness and tartness.',
        2),
       ('Chicken Enchiladas with Green Sauce',
        'Soft Tortillas filled with seasoned shredded Chicken, rolled up, and smothered with a tangy Green enchilada sauce, topped with melted Cheese and garnished with fresh Cilantro. A crowd-pleasing Mexican-inspired dish.',
        2),
       ('Spinach and Mushroom Stuffed Shells',
        'Jumbo Pasta shells filled with a mixture of sautéed Spinach, Mushrooms, Ricotta Cheese, and herbs, baked in a marinara sauce and topped with melted Mozzarella. A comforting vegetarian pasta dish.',
        2),
       ('Apple Cranberry Walnut Salad',
        'Crisp Lettuce greens tossed with sliced Apples, dried Cranberries, toasted Walnuts, crumbled Goat Cheese, and a tangy Apple Cider Vinaigrette. A perfect salad for the fall season.',
        2),
       ('Moroccan Spiced Roasted Carrots',
        'Roasted Carrot spears seasoned with a blend of Moroccan spices, such as Cumin, Paprika, and Cinnamon, drizzled with Olive Oil, and garnished with fresh Parsley. A flavorful and colorful side dish.',
        2),
       ('Strawberry Spinach Salad with Balsamic Vinaigrette',
        'A refreshing salad featuring baby Spinach leaves, sliced Strawberries, crumbled Feta Cheese, and a tangy Balsamic Vinaigrette dressing. The combination of sweet and savory flavors makes it a delightful choice.',
        2),
       ('Coconut Curry Lentil Soup',
        'A hearty and comforting soup made with Red Lentils, Coconut milk, and aromatic spices like Curry powder, Turmeric, and Ginger. Perfect for a cozy dinner on a cold day.',
        2),
       ('Chocolate Dipped Coconut Macaroons',
        'Chewy and sweet Coconut macaroons dipped in smooth, melted Chocolate, and optionally sprinkled with toasted Coconut flakes. A delightful treat for coconut and chocolate lovers alike.',
        2),
       ('Grilled Lemon Herb Salmon',
        'Fresh Salmon fillets marinated in a mixture of Lemon juice, Garlic, and a blend of herbs like Thyme and Rosemary, then grilled to perfection. Served with a side of roasted Vegetables or a refreshing Salad.',
        2),
       ('Blueberry Lemon Pancakes',
        'Fluffy Pancakes studded with juicy Blueberries and infused with bright Lemon zest, served with a drizzle of Maple syrup. A delightful breakfast or brunch option.',
        2),
       ('Caprese Skewers',
        'Skewers of Cherry Tomatoes, fresh Mozzarella balls, and Basil leaves, drizzled with Balsamic glaze and sprinkled with Salt and Pepper. A colorful and flavorful appetizer or party snack.',
        2),
       ('Chicken and Vegetable Curry',
        'A flavorful curry made with tender Chicken pieces, an assortment of colorful Vegetables like Bell Peppers, Carrots, and Potatoes, simmered in a fragrant blend of Indian spices and Coconut milk. Serve over steamed Rice or with Naan bread.',
        2),
       ('Raspberry Balsamic Glazed Chicken',
        'Juicy Chicken breasts marinated in a tangy Raspberry Balsamic glaze, grilled to perfection, and served with a side of roasted Vegetables or a fresh Salad. A flavorful and light main course.',
        2),
       ('Summer Berry Tart',
        'A buttery Tart crust filled with a creamy Vanilla Custard and topped with an assortment of fresh Summer Berries like Strawberries, Blueberries, and Raspberries. A visually stunning and delicious dessert.',
        2),
       ('Stuffed Bell Peppers with Quinoa and Black Beans',
        'Bell Peppers filled with a mixture of cooked Quinoa, Black Beans, Corn, diced Tomatoes, and spices, topped with melted Cheese and baked until the Peppers are tender. A nutritious and flavorful vegetarian dish.',
        2),
       ('Creamy Mushroom Risotto',
        'Creamy Arborio Rice cooked with sautéed Mushrooms, Onions, Garlic, and a splash of White Wine, finished with Parmesan Cheese and fresh Herbs. A comforting and indulgent Italian dish.',
        2),
       ('Avocado Tomato Salad',
        'A vibrant salad featuring ripe Avocado slices, juicy Tomato wedges, thinly sliced Red Onion, and fresh Basil leaves, dressed with a simple vinaigrette of Olive Oil, Lemon juice, and a hint of Dijon Mustard.',
        2),
       ('Beef Stir-Fry with Broccoli and Bell Peppers',
        'Tender Beef strips stir-fried with crisp Broccoli florets, colorful Bell Peppers, and a savory sauce made of Soy sauce, Garlic, Ginger, and Sesame oil. Serve over steamed Rice or noodles for a satisfying meal.',
        2),
       ('Grilled Shrimp Tacos',
        'Succulent Grilled Shrimp marinated in a zesty blend of Lime juice, Garlic, and Chili powder, served in warm Tortillas with fresh Cabbage slaw, Avocado slices, and a drizzle of creamy Chipotle sauce. A delightful and flavorful taco option.',
        2),
       ('Creamy Chicken and Mushroom Casserole',
        'Tender Chicken pieces and sautéed Mushrooms baked in a creamy sauce made with Chicken broth, Cream, and a touch of White wine. Topped with a golden breadcrumb and Parmesan Cheese crust for a satisfying comfort food dish.',
        2),
       ('Veggie Frittata',
        'A fluffy and nutritious Frittata loaded with an assortment of colorful Vegetables such as Bell Peppers, Spinach, Tomatoes, and Zucchini, combined with beaten Eggs and a sprinkle of grated Cheese. Baked to perfection and perfect for brunch or a light dinner.',
        2),
       ('Caramelized Onion and Mushroom Tart',
        'A savory Tart with a buttery crust, topped with caramelized Onions, sautéed Mushrooms, and melted Gruyere Cheese. Baked to perfection and garnished with fresh Thyme leaves for a delightful appetizer or light lunch option.',
        2),
       ('Honey Lime Grilled Chicken Skewers',
        'Tender Chicken pieces marinated in a mixture of Honey, Lime juice, Garlic, and a blend of spices, threaded onto skewers and grilled to perfection. Served with a side of Coconut Rice or a fresh Mango Salsa for a tropical-inspired meal.',
        2),
       ('Chocolate Peanut Butter Banana Smoothie',
        'A creamy and indulgent smoothie made with ripe Bananas, rich Chocolate, and smooth Peanut Butter, blended with Milk and a drizzle of Honey. A satisfying and decadent treat for breakfast or as a post-workout snack.',
        2),
       ('Italian Stuffed Bell Peppers',
        'Bell Peppers stuffed with a flavorful mixture of Ground Beef, cooked Rice, diced Tomatoes, Onion, and a blend of Italian herbs and spices. Baked until tender and topped with melted Cheese for a delicious and satisfying meal.',
        5),
       ('Blueberry Lemon Scones',
        'Buttery and flaky Scones packed with juicy Blueberries and bright Lemon zest, drizzled with a tangy Lemon glaze. Perfect for breakfast or as an afternoon tea treat.',
        2),
       ('Raspberry Almond Thumbprint Cookies',
        'Butter cookies filled with sweet Raspberry jam and topped with a crunchy Almond. Baked until golden and delicate. Perfect for enjoying with a cup of Tea or gifting to loved ones.',
        2),
       ('Cajun Shrimp Pasta',
        'A spicy and flavorful Pasta dish featuring succulent Cajun-seasoned Shrimp, sautéed Bell Peppers and Onions, tossed with Linguine or Penne Pasta in a creamy Tomato sauce. A satisfying and satisfyingly delicious dinner option.',
        2),
       ('Moroccan Chickpea Stew',
        'A hearty and aromatic stew made with Chickpeas, colorful Vegetables, such as Carrots, Zucchini, and Bell Peppers, and a blend of Moroccan spices like Cumin, Coriander, and Paprika. Serve over cooked Couscous or with crusty Bread for a satisfying vegetarian meal.',
        2),
       ('Raspberry White Chocolate Muffins',
        'Moist and tender Muffins bursting with juicy Raspberries and sweet White Chocolate chunks. A delightful treat for breakfast or as a snack any time of the day.',
        2),
       ('Thai Green Curry with Vegetables and Tofu',
        'A fragrant and flavorful Thai Green Curry made with a medley of fresh Vegetables like Bell Peppers, Zucchini, and Eggplant, along with cubed Tofu, simmered in a creamy and spicy Green Curry sauce. Serve over steamed Jasmine Rice for a delicious and satisfying meal.',
        2),
       ('Spinach and Feta Stuffed Mushrooms',
        'Button Mushrooms filled with a savory mixture of sautéed Spinach, crumbled Feta Cheese, Garlic, and Herbs, baked until tender and golden. A tasty and elegant appetizer for parties or gatherings.',
        2),
       ('Honey Balsamic Roasted Carrots',
        'Tender Carrot sticks roasted with a glaze made of Honey, Balsamic vinegar, and a hint of Garlic. A sweet and tangy side dish that pairs well with roasted meats or grilled vegetables.',
        2),
       ('Chicken Caesar Salad Wraps',
        'Grilled Chicken strips, crisp Romaine Lettuce, Parmesan Cheese, and a creamy Caesar dressing wrapped in a Tortilla or Lettuce leaf. A convenient and flavorful option for a quick and satisfying meal.',
        2),
       ('Moroccan Lamb Tagine',
        'A flavorful and aromatic Moroccan-style stew made with tender Lamb, a medley of Vegetables like Carrots, Onions, and Eggplant, seasoned with Moroccan spices, such as Cinnamon, Cumin, and Ginger. Slow-cooked to perfection and served with fluffy Couscous or crusty Bread.',
        2),
       ('Honey Mustard Glazed Salmon',
        'Grilled or baked Salmon fillets glazed with a mixture of Honey, Dijon Mustard, and a touch of Garlic, served with a side of roasted Potatoes or steamed Vegetables. A sweet and tangy dish that showcases the natural flavors of Salmon.',
        2),
       ('Caprese Quinoa Salad',
        'A fresh and vibrant Salad featuring cooked Quinoa, Cherry Tomatoes, Mozzarella balls, fresh Basil leaves, and a drizzle of Balsamic glaze. A light and nutritious option for a quick lunch or a side dish.',
        2),
       ('Caramelized Onion and Goat Cheese Flatbread',
        'Thin and crispy Flatbread topped with sweet and savory Caramelized Onions, crumbled Goat Cheese, and a sprinkle of fresh Thyme. Baked until golden and served as an appetizer or light meal.',
        2),
       ('Teriyaki Veggie Stir-Fry',
        'A colorful and nutritious Stir-Fry featuring an array of Vegetables like Broccoli, Bell Peppers, Carrots, and Snap Peas, stir-fried in a homemade Teriyaki sauce and served over steamed Rice or Noodles. A quick and flavorful vegetarian option.',
        2),
       ('Lemon Poppy Seed Pound Cake',
        'A moist and tender Pound Cake infused with the bright flavors of Lemon zest and dotted with crunchy Poppy Seeds. Perfect for dessert or as a sweet treat with a cup of Tea or Coffee.',
        2);


WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Cheerful hunter')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Anchovies', 'Tomato', 'Apple', 'Mozzarella', 'Hercules', 'Vodka',
                            'Vegetable oil', 'Bread', 'Rice'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Grilled Vegetable Medley')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Eggplant', 'Tomato', 'Zucchini', 'Bell Pepper', 'Asparagus', 'Vodka',
                            'Cognac', 'Soda', 'Honey'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Creamy Potato Salad')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Potato flour', 'Potato', 'Onion', 'Cucumber', 'Sour cream', 'Vodka',
                            'Cognac', 'Soda', 'Honey', 'Hercules', 'Rice', 'Barley groats', 'Plum'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Fruit Salad Delight')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Apricot', 'Pear', 'Apple', 'Grape', 'Orange', 'Banana',
                            'Strawberry', 'Kiwi', 'Honey', 'earl barley', 'Pineapple', 'Beer', 'Wine'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Cheesy Broccoli Bake')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Broccoli', 'Cream Cheese', 'Bread', 'Coffee', 'Cocoa', 'Sugar',
                            'Chocolate', 'Honey'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Lemony Chicken Piccata')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Chicken', 'Lemon ', 'Hercules', 'Rice', 'Millet', 'Butter',
                            'Tomato', 'Vodka'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Creamy Mushroom Pasta')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Mushrooms', 'Vegetable oil', 'Butter', 'Cream', 'Cream Cheese', 'Gouda',
                            'Spinach', 'Liquor'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Sweet and Spicy Glazed Ham')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Ham', 'Honey', 'Sugar', 'Shrimps', 'Oysters', 'Poppy',
                            'Wheat flour', 'Tea'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Seafood Paella')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Rice', 'Shrimps', 'Mussels', 'Fish', 'Bell Pepper', 'Tomato',
                            'Asparagus', 'Wine', 'Beer'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Creamy Spinach Dip')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Spinach', 'Cream Cheese', 'Sour cream', 'Grape', 'Mozzarella', 'Salami',
                            'Veal', 'Bread', 'Coffee'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Roasted Cauliflower with Garlic and Parmesan')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Spinach', 'Cream Cheese', 'Cauliflower', 'Vegetable oil', 'Cheese', 'Provolone',
                            'Cocoa', 'Bread', 'Vodka'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Stuffed Bell Peppers')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Bell Peppers', 'Beef', 'Rice', 'Onion', 'Cheese', 'Liquor',
                            'Coffee', 'Eggs'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Mango Salsa Chicken')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Chicken', 'Mango', 'Onion', 'Orange', 'Pineapple', 'Peach',
                            'Feta Cheese', 'Yogurt'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Creamy Garlic Shrimp Pasta')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Shrimp', 'Pasta', 'Crab sticks', 'Caviar', 'Noodles', 'Lettuce',
                            'Wine', 'Liquor'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Honey Glazed Carrots')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Carrot', 'Honey', 'Butter', 'Pepperoni', 'Sausage', 'Buckwheat',
                            'Semolina', 'Milk'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Blueberry Pancakes')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Blueberry', 'Strawberry', 'Banana', 'Tea', 'Coffee', 'Cocoa',
                            'Bread', 'Milk'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Apple Cinnamon Muffins')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Apple', 'Wheat flour', 'Eggs', 'Vegetable oil', 'Sugar', 'Soda',
                            'Butter', 'Condensed Milk'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Lemon Garlic Butter Salmon')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Fish', 'Lemon', 'Pineapple', 'Kiwi', 'Butter', 'Asparagus',
                            'Potato', 'Vodka'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Beef Stir-Fry with Vegetables')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Beef', 'Tomato', 'Onion', 'Carrot', 'Cabbage', 'Cauliflower',
                            'Rice', 'Noodles','Barley groats'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Caprese Salad')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Tomato', 'Mozzarella', 'Vegetable oil', 'Wine', 'Cognac'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Greek Salad')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Lettuce', 'Tomato', 'Cucumber', 'Feta Cheese', 'Orange', 'Vegetable oil',
                            'Chorizo', 'Pastrami','Ground Beef'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Garlic Butter Steak')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Butter', 'Potato', 'Cucumber', 'Tomato', 'Radish', 'Vegetable oil',
                            'Pork', 'Veal','Beef','Lamb'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Creamy Mushroom Soup')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Mushrooms', 'Onion', 'Cream', 'Semolina', 'Potato flour', 'Vegetable oil',
                            'Bread', 'Poppy'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Spinach and Feta Stuffed Chicken Breast')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Chicken', 'Spinach', 'Feta Cheese', 'Cream Cheese', 'Butter', 'Vegetable oil',
                            'Bread', 'Cognac'
    );

WITH recipe_data AS (SELECT recipe_id
                     FROM public.recipes
                     WHERE recipe_name = 'Strawberry Shortcake')
-- Insert ingredient-recipe associations
INSERT
INTO public.ingredient_recipe (ingredient_id, recipe_id)
SELECT i.ingredient_id, r.recipe_id
FROM public.ingredients i
         CROSS JOIN recipe_data r
WHERE i.ingredient_name IN (
                            'Strawberry', 'Ice Cream', 'Cream', 'Beer', 'Blueberry', 'Coffee'
    );







