import java.util.ArrayList;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        List<Account> accountList = new ArrayList<>();
        Account account1 = new Account("Jenson", "Black", "USA", 5000, 'm');
        account1.setBirthday("1999-01-07");
        Account account2 = new Account("Isaac", "Bradley", "USA", 500, 'm');
        account2.setBirthday("2000-02-07");
        Account account3 = new Account("Elsie", "Hamilton", "Brazil", 1000, 'w');
        account3.setBirthday("2001-03-07");
        Account account4 = new Account("Jay", "Johnson", "France", 2000, 'm');
        account4.setBirthday("1989-04-07");
        Account account5 = new Account("Dominic", "Wilkinson", "Brazil", 3000, 'm');
        account5.setBirthday("1987-05-07");
        Account account6 = new Account("Selena", "Rodriguez", "France", 400, 'w');
        account6.setBirthday("1985-01-07");
        Account account7 = new Account("Jonathon", "Vega", "Brazil", 600, 'm');
        account7.setBirthday("1994-02-07");
        Account account8 = new Account("Payton", "Winters", "USA", 900, 'm');
        account8.setBirthday("1993-03-07");
        Account account9 = new Account("Nicole", "Johnson", "Brazil", 100, 'w');
        account9.setBirthday("1987-01-07");
        Account account10 = new Account("Cohen", "Walton", "Brazil", 1500, 'm');
        account10.setBirthday("1985-04-07");
        Account account11 = new Account("Jonathan", "Johnson", "France", 20, 'm');
        account11.setBirthday("1982-01-07");
        Account account12 = new Account("Amelia", "Hawkins", "USA", 14000, 'w');
        account12.setBirthday("1983-05-07");
        accountList.add(account1);
        accountList.add(account2);
        accountList.add(account3);
        accountList.add(account4);
        accountList.add(account5);
        accountList.add(account6);
        accountList.add(account7);
        accountList.add(account8);
        accountList.add(account9);
        accountList.add(account10);
        accountList.add(account11);
        accountList.add(account12);
        for (Account element : accountList) {
            System.out.println(element);
        }
        System.out.println();
        System.out.println("*********************Method1****************************");
        for (Account account : AccountUtils.returnListAccountsWithBalanceGreater1000(accountList)) {
            System.out.println(account);
        }
        System.out.println();
        System.out.println("*********************Method2****************************");
        for (String account : AccountUtils.returnListFirstLastNameInBrazil(accountList)) {
            System.out.println(account);
        }
        System.out.println();
        System.out.println("*********************Method3****************************");
        System.out.println(AccountUtils.returnOptionalAccountWithLargestBalance(accountList));
        System.out.println();
        System.out.println("*********************Method4****************************");
        AccountUtils.returnAllUsersWithSpecMonthOfBirth(accountList, 1);
        System.out.println();
        System.out.println("*********************Method5****************************");
        System.out.println(AccountUtils.returnNumberOfAccountsWithFemaleGender(accountList));
        System.out.println();
        System.out.println("*********************Method6****************************");
        System.out.println(AccountUtils.returnTotalAmountOnAccountsJohnson(accountList));
        System.out.println();
        System.out.println("*********************Method7****************************");
        for (Account account : AccountUtils.returnSortedListOfUsersByLastThenFirstName(accountList)) {
            System.out.println(account);
        }
        System.out.println();
        System.out.println("*********************Method8****************************");
        AccountUtils.returnGroupedMapByCountry(accountList);
        System.out.println();
        System.out.println("*********************Method9****************************");
        List<Account> accountList2 = new ArrayList<>();
        Account account13 = new Account("Jenson2", "Black2", "USA", 5000, 'm');
        account13.setBirthday("1999-01-07");
        Account account14 = new Account("Isaac2", "Bradley2", "USA", 500, 'm');
        account14.setBirthday("2000-02-07");
        Account account15 = new Account("Elsie2", "Hamilton2", "Brazil", 1000, 'w');
        account15.setBirthday("2001-03-07");
        Account account16 = new Account("Jay2", "Johnson2", "France", 2000, 'm');
        account16.setBirthday("1989-04-07");
        Account account17 = new Account("Dominic2", "Wilkinson2", "Brazil", 3000, 'm');
        account17.setBirthday("1987-05-07");
        Account account18 = new Account("Selena2", "Rodriguez2", "France", 400, 'w');
        account18.setBirthday("1985-01-07");
        Account account19 = new Account("Jonathon2", "Vega22", "Brazil", 600, 'm');
        account19.setBirthday("1994-02-07");
        Account account20 = new Account("Payton2", "Winters2", "USA", 900, 'm');
        account20.setBirthday("1993-03-07");
        Account account21 = new Account("Nicole2", "Johnson2", "Brazil", 100, 'w');
        account21.setBirthday("1987-01-07");
        Account account22 = new Account("Cohen2", "Walton2", "Brazil", 1500, 'm');
        account22.setBirthday("1985-04-07");
        Account account23 = new Account("Jonathan2", "Johnson2", "France", 20, 'm');
        account23.setBirthday("1982-01-07");
        Account account24 = new Account("Amelia2", "Hawkins2", "USA", 14000, 'w');
        account24.setBirthday("1983-05-07");
        accountList2.add(account13);
        accountList2.add(account14);
        accountList2.add(account15);
        accountList2.add(account16);
        accountList2.add(account17);
        accountList2.add(account18);
        accountList2.add(account19);
        accountList2.add(account20);
        accountList2.add(account21);
        accountList2.add(account22);
        accountList2.add(account23);
        accountList2.add(account24);
        List<Account> accountList3 = new ArrayList<>();
        Account account25 = new Account("Jenson2", "Black2", "USA", 5000, 'm');
        account25.setBirthday("1999-01-07");
        Account account26 = new Account("Isaac2", "Bradley2", "USA", 500, 'm');
        account26.setBirthday("2000-02-07");
        Account account27 = new Account("Elsie2", "Hamilton2", "Brazil", 1000, 'w');
        account27.setBirthday("2001-03-07");
        Account account28 = new Account("Jay2", "Johnson2", "France", 2000, 'm');
        account28.setBirthday("1989-04-07");
        Account account29 = new Account("Dominic2", "Wilkinson2", "Brazil", 3000, 'm');
        account29.setBirthday("1987-05-07");
        Account account30 = new Account("Selena2", "Rodriguez2", "France", 400, 'w');
        account30.setBirthday("1985-01-07");
        Account account31 = new Account("Jonathon2", "Vega22", "Brazil", 600, 'm');
        account31.setBirthday("1994-02-07");
        Account account32 = new Account("Payton2", "Winters2", "USA", 900, 'm');
        account32.setBirthday("1993-03-07");
        Account account33 = new Account("Nicole2", "Johnson2", "Brazil", 100, 'w');
        account33.setBirthday("1987-01-07");
        Account account34 = new Account("Cohen2", "Walton2", "Brazil", 1500, 'm');
        account34.setBirthday("1985-04-07");
        Account account35 = new Account("Jonathan2", "Johnson2", "France", 20, 'm');
        account35.setBirthday("1982-01-07");
        Account account36 = new Account("Amelia2", "Hawkins2", "USA", 14000, 'w');
        account36.setBirthday("1983-05-07");
        accountList3.add(account25);
        accountList3.add(account26);
        accountList3.add(account27);
        accountList3.add(account28);
        accountList3.add(account29);
        accountList3.add(account30);
        accountList3.add(account31);
        accountList3.add(account32);
        accountList3.add(account33);
        accountList3.add(account34);
        accountList3.add(account35);
        accountList3.add(account36);
        List<List<Account>> listOfListsOfAccounts = new ArrayList<>();
        listOfListsOfAccounts.add(accountList);
        listOfListsOfAccounts.add(accountList2);
        listOfListsOfAccounts.add(accountList3);
        System.out.println(AccountUtils.returnNumberOfAccountsWithAgeAbove30Years(listOfListsOfAccounts));
    }
}