CREATE DATABASE reg_app_db;

CREATE TABLE public.user
(
    user_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     varchar(255) NOT NULL UNIQUE,
    "password"   varchar(255) NOT NULL,
    lastname     varchar(255) NOT NULL,
    firstname    varchar(255) NOT NULL,
    birthday     date,
    email        varchar(255) NOT NULL,
    phone_number varchar(255),
    address      varchar(255),
    is_available boolean
);

INSERT INTO public.user (username, "password", lastname, firstname, birthday, email, phone_number, address,
                         is_available)
VALUES ('elblack', 'qwerty!', 'Black', 'Elsie', '1999-01-07', 'black@gmail.com', '+380631112233', '27308 County Rd #4
Rushford, Minnesota(MN), 55971', true),
       ('samjay', 'qwerty@', 'Samilton', 'Jay', '1999-02-08', 'wradley@gmail.com', '+380631112277', '203 W Front St
Oil City, Pennsylvania(PA), 16301', false),
       ('elssam', 'qwerty#', 'Samilton', 'Elsie', '2003-09-22', 'samilton@ukr.net', '+380631112244', '429 Grove St
Greensburg, Pennsylvania(PA), 15601', true),
       ('jayjohn', 'qwerty$', 'Johnson', 'Jay', '1999-02-10', 'johnson@mail.ua', '+380631119944', '16 Coyote Run
Spencerport, New York(NY), 14559', true),
       ('domwilk', 'qwerty%', 'Wilkinson', 'Dominic', '1965-09-15', 'wilkinson@mail.com', '+380631112255', '18255 Denby
Redford, Michigan(MI), 48240', false),
       ('rodjay', 'qwerty%', 'Rodriguez', 'Jay', '1999-02-10', 'rodriguez@yep.uk', '+380981112255', '3883 Ferdinand Dr
Port Hope, Michigan(MI), 48468', true),
       ('elssega', 'qwerty!', 'Sega', 'Elsie', '1997-06-17', 'sega6@york.com', NULL, '1208 Park Ave
Gadsden, Alabama(AL), 35903', true),
       ('paywinters', 'qwerty#', 'Winters', 'Payton', '1999-02-19', 'winters7@york.com', '+380631112299', '324 4th St SW
Spencer, Iowa(IA), 51301', false),
       ('adamsend', 'qwerty@#', 'Sendler', 'Adam', '2000-02-13', 'adam@gmail.com', NULL, '32 Vanderburgh Ave
Larchmont, New York(NY), 10538', true);

-- 1.Get a list of all the usernames in the list of Users.
SELECT username
FROM public.user;

-- 2.Filter the list of User objects to only include users whose last name starts with "S".
SELECT *
FROM public.user
WHERE lastname LIKE 'S%';

-- 3.Get a list of all the User objects in the list that have an email address ending in ".com"
SELECT *
FROM public.user
WHERE email LIKE '%.com';

-- 4.Get a list of all the User objects in the list that are available
SELECT *
FROM public.user
WHERE is_available = TRUE;

-- 5.Filter the list of User objects to only include users whose phoneNumber value is not null or empty
SELECT *
FROM public.user
WHERE phone_number IS NOT NULL;

-- 6.Sort users by last name, and firstname
SELECT *
FROM public.user
ORDER BY lastname, firstname ASC;


-- 7.Find the User objects in the list that have a firstName field that matches a given regular expression pattern
SELECT *, (SELECT SUBSTRING(firstname, '[a-zA-Z]{5,}'))
FROM public.user;

SELECT *, (SELECT regexp_match(firstname, '[a-zA-Z]{5,}'))
FROM public.user;

SELECT *
FROM public.user
WHERE firstname ~ '[a-zA-Z]{5,}';

-- 8.Find the User object in the list with the earliest date field
SELECT *
FROM public.user
WHERE birthday = (SELECT MIN(birthday) FROM public.user);

-- 9.Find the User objects in the list that have a date field in the same year as a given date, and then count their amount
SELECT *
FROM public.user
where date_part('YEAR',birthday)='1999';

SELECT COUNT(birthday)
FROM public.user
where date_part('YEAR',birthday)='1999';