CREATE DATABASE linkedInDB;

CREATE TABLE public.jobTitle
(
    job_title_id    bigint primary key generated by default as identity,
    job_title_name  varchar(255),
    job_title_level varchar(255)
);

INSERT INTO jobTitle(job_title_name, job_title_level)
VALUES ('Java Developer', 'junior'),
       ('Java Developer', 'middle'),
       ('Java Developer', 'senior'),
       ('Python Developer', 'junior'),
       ('Python Developer', 'middle'),
       ('Python Developer', 'senior'),
       ('JavaScript Developer', 'junior'),
       ('JavaScript Developer', 'middle'),
       ('JavaScript Developer', 'senior');

CREATE TABLE public.vacancies
(
    vacancy_id   bigint primary key generated by default as identity,
    vacancy_name varchar(255),
    job_title_id bigint,
    foreign key (job_title_id) references jobTitle (job_title_id)
);

INSERT INTO vacancies(vacancy_name, job_title_id)
values ('Junior Java Developer', 1),
       ('Middle Java Developer', 2),
       ('Junior Python Developer', 4),
       ('Junior JavaScript Developer', 7),
       ('Middle JavaScript Developer', 8);

CREATE TABLE public.users
(
    user_id      bigint primary key generated by default as identity,
    first_name   varchar(255),
    last_name    varchar(255),
    phone_number varchar,
    job_title_id bigint,
    foreign key (job_title_id) references jobTitle (job_title_id)
);

INSERT INTO users(first_name, last_name, phone_number, job_title_id)
values ('Mila', 'Kunis', '0973385000', 2),
       ('George', 'Clooney', '09333325698', 1),
       ('Ryan', 'Gossling', '0682255678', 3),
       ('Emma', 'Watson', '0972233555', 4),
       ('Robert', 'Downey Jr.', '0503366999', 6),
       ('Michael', 'Holz', '0633232333', 9),
       ('Mary', 'Saveley', '0974455666', 5);

CREATE table public.messages
(
    message_id          bigint primary key generated by default as identity,
    from_user_id        bigint,
    to_user_id          bigint,
    foreign key (from_user_id) references users (user_id),
    foreign key (to_user_id) references users (user_id),
    message_description varchar(255),
    message_date        timestamp with time zone
);

INSERT INTO messages(from_user_id, to_user_id, message_description, message_date)
VALUES (1, 2, 'Hi George!', '2022-10-19 10:23:54 GMT'),
       (2, 1, 'Hello Mila! How are the interviews?', '2022-10-19 10:25:54 GMT'),
       (1, 2, 'Thank you, everything is fine, I received the offer!', '2022-10-19 10:27:54 GMT'),
       (3, 4, 'Emma, when will you return my umbrella?', '2023-03-11 19:25:54 GMT'),
       (4, 3, 'I forgot your umbrella at work! Sorry!', '2023-03-11 19:30:54 GMT'),
       (3, 4, 'It''s going to rain this week!', '2023-03-11 19:31:54 GMT');

CREATE TABLE public.posts
(
    post_id          bigint primary key generated by default as identity,
    from_user_id     bigint,
    to_user_id       bigint,
    foreign key (from_user_id) references users (user_id),
    foreign key (to_user_id) references users (user_id),
    post_description varchar(4000),
    post_date        timestamp with time zone
);

INSERT INTO posts(from_user_id, to_user_id, post_description, post_date)
values (7, 5,
        'Are you preparing for a Java developer role or looking to refresh your knowledge of the language? Check out this top Java interview questions that covers everything from basic concepts to advanced topics.',
        '2023-03-30 10:31:54 GMT'),
       (5, 7,
        'Whether you''re a seasoned professional or just starting out, these questions will help you evaluate your understanding of the language and prepare for your next interview.',
        '2023-03-30 10:55:54 GMT'),
       (4, 6,
        'I’m happy to share that I’ve obtained a new certification: Verified International Academic Qualifications from World Education Services!',
        '2022-12-11 12:31:54 GMT'),
       (6, 4,
        ' Together with our lovely HRM Team, we were joined by Anna to discuss the future of DataArt and how we can help DataArt achieve its long-term goals.',
        '2023-02-16 14:31:54 GMT'),
       (2, 1, 'hello colleagues !
Data is the lifeblood of modern businesses, but it can be overwhelming to manage latest blog post offers insights on how to navigate the complex world of structured and unstructured data to drive growth and innovation.
Check and Like :)', '2023-04-01 09:31:54 GMT');