import cars.Car;
import laptops.Laptop;
import products.Apple;
import products.Fruit;
import products.Plum;
import products.Vegetable;
import triangles.Triangle;

public class Main {
    public static void main(String[] args) {
        System.out.println("********Task1********");
        Fruit fruit1 = new Fruit(1, 2, "red", false, "sweet", true);
        fruit1.growingPlace();
        Vegetable vegetable1 = new Vegetable(3, 5, "green", true, true, "Dnipro");
        vegetable1.growingPlace();
        fruit1.cooking();
        fruit1.smells();
        vegetable1.healthy();
        Apple apple1 = new Apple(1, 2, "green", true, "sweet", true, "circle");
        apple1.cooking();
        apple1.growingPlace();
        apple1.smells();
        apple1.season();
        apple1.setWeight(15);
        apple1.setSize(10);
        System.out.println(apple1.getWeight());
        System.out.println(apple1.getSize());
        Plum plum1 = new Plum(2, 1, "blue", true, "sweet", false, true);
        plum1.cooking();
        plum1.growingPlace();
        plum1.smells();
        plum1.juiciness();
        System.out.println();
        System.out.println("********Task2********");
        Car car1 = new Car(240, 80, 2021, 22000, "Kia");
        System.out.println("Max speed: " + car1.getMaxSpeed());
        System.out.println("Fuel amount: " + car1.getFuelAmount());
        System.out.println("Production year: " + car1.getProductionYear());
        System.out.println("Price: " + car1.getPrice());
        System.out.println("Brand: " + car1.getBrand());
        car1.startStopEngine();
        car1.setCurrentSpeed(100);
        System.out.println("Current speed: " + car1.getCurrentSpeed());
        car1.startStopEngine();
        car1.startStopEngine();
        car1.setCurrentSpeed(80);
        System.out.println("Current speed: " + car1.getCurrentSpeed());
        car1.increaseAccelerating();
        car1.decreaseAccelerating();
        car1.startBeeping();
        System.out.println();
        System.out.println("********Task3********");
        Laptop laptop1 = new Laptop("Lenovo", false, "Hello World!", 30);
        System.out.println("Brand: " + laptop1.getBrand());
        System.out.println("IsTurnedOn: " + laptop1.getIsTurnedOn());
        System.out.println("Welcome Phrase: " + laptop1.getWelcomePhrase());
        System.out.println("Buttery amount: " + laptop1.getButteryAmount());
        laptop1.TurnOn();
        System.out.println("IsTurnedOn: " + laptop1.getIsTurnedOn());
        laptop1.TurnOn();
        laptop1.decreaseButteryAmount();
        laptop1.decreaseButteryAmount();
        laptop1.decreaseButteryAmount();
        laptop1.decreaseButteryAmount();
        laptop1.decreaseButteryAmount();
        laptop1.decreaseButteryAmount();
        System.out.println("IsTurnedOn: " + laptop1.getIsTurnedOn());
        System.out.println();
        System.out.println("********Task4********");
        Triangle triangle1 = new Triangle(3,4,5);
        System.out.println("Side A: " + triangle1.getSideA());
        System.out.println("Side B: " + triangle1.getSideB());
        System.out.println("Side C: " + triangle1.getSideC());
        triangle1.getPerimeter();
        triangle1.getSquare();
        triangle1.verifyPythagoras();
        Triangle triangle2 = new Triangle(3,4,8);
        System.out.println("Side A: " + triangle2.getSideA());
        System.out.println("Side B: " + triangle2.getSideB());
        System.out.println("Side C: " + triangle2.getSideC());
        triangle2.getPerimeter();
        triangle2.getSquare();
        triangle2.verifyPythagoras();
    }
}